added task 4.1
afrikanov/Spbu-sem2 pull request #10
Opened 2019-04-10 23:02 UTC by afrikanov

2019-05-02 09:34 UTC, SpirinEgor requested changes
В целом:
1. Непонятно зачем такскать в репо все градловские файлы, особенно которые автогенерируются и специфичны для ОС.
2. Все `else` написаны не по style guide.

2019-05-02 09:34 UTC, SpirinEgor commented on hw04/task1/src/main/java/group144/afrikanov/LinkedList.java
> +/** * Class implements methods of a list. */
Опять лишние звёздочки

2019-05-02 09:34 UTC, SpirinEgor commented on hw04/task1/src/main/java/group144/afrikanov/LinkedList.java
> +            certainNode.previous.next = certainNode.next;
Для этого же функция выше определена, а так получается, что один и тот же код в разные места скопировал.

2019-05-02 09:34 UTC, SpirinEgor commented on hw04/task1/src/main/java/group144/afrikanov/LinkedList.java
> +    public void removeNode(Node item) {
Ещё надо размер уменьшить.

2019-05-02 09:34 UTC, SpirinEgor commented on hw04/task1/src/main/java/group144/afrikanov/LinkedList.java
> +     * @param value - value which is need to add
Почти для всех функций, которые кидают ошибку это не описано в JavaDoc.

2019-05-02 09:34 UTC, SpirinEgor commented on hw04/task1/src/main/java/group144/afrikanov/LinkedList.java
> +    boolean empty() {
Лучше `isEmpty()`

2019-05-02 09:34 UTC, SpirinEgor commented on hw04/task1/src/main/java/group144/afrikanov/LinkedList.java
> +            Node result = head;
Опять же, у тебя есть функция, которая ищет ноду по индексу, а здесь точно такой же код. Лучше найти ноду, а потом от неё взять `value`.

2019-05-02 09:34 UTC, SpirinEgor commented on hw04/task1/src/main/java/group144/afrikanov/LinkedList.java
> +     * @param value - value which is need to add
Ну собственно они и не кидают ошибку. Как я понял, это должен делать `UniqueList`, но тогда непонятно зачем описывать это здесь

2019-05-02 09:34 UTC, SpirinEgor commented on hw04/task1/src/main/java/group144/afrikanov/LinkedList.java
> +        newItem.previous = item;
`Node newItem = new Node(value, item.next, item)`

2019-05-02 09:34 UTC, SpirinEgor commented on hw04/task1/src/main/java/group144/afrikanov/LinkedList.java
> +        Node newItem = new Node(value, null, null);
```
tail = new Node(value, null, tail);
if (head == null) {
    head = tail;
} else {
    tail.previous.next = tail;
}
++size;
```
Подобным способом можно во всех `insert` функциях заменить, стало куда меньше кода и всех этих переприсваиваний, однако через чур короткий код может стать непонятным, так что можешь немного поразбивать такие строчки.

2019-05-02 09:34 UTC, SpirinEgor commented on hw04/task1/src/main/java/group144/afrikanov/LinkedList.java
> +        else {
Согласно
https://google.github.io/styleguide/javaguide.html#s4.1.2-blocks-k-r-style
`else` пишется в той же строчке

2019-05-02 09:34 UTC, SpirinEgor commented on hw04/task1/src/test/java/group144/afrikanov/LinkedListTest.java
> +class LinkedListTest<T> {
Не знаю насколько необходимо, но такие тесты выглядят так себе.
Во-первых большая часть функций не покрывается ими, особенно проблемно - каждый тест использует `insertBack` и `insertFront`, но они не проверяются.
Во-вторых не хватает каких-то больших тестов, можно написать цикл, положить в лист порядка 1е5 случайных значений и уже там проверить какие-то функции.

2019-05-02 12:39 UTC, afrikanov commented on hw04/task1/src/main/java/group144/afrikanov/LinkedList.java
> +     * @param value - value which is need to add
Так ведь UniqueList переопределяет метод, который кидает исключение

2019-05-02 14:03 UTC, afrikanov commented on hw04/task1/src/test/java/group144/afrikanov/LinkedListTest.java
> +class LinkedListTest<T> {
А зачем делать именно большие тесты? Они же пишутся для проверки времени работы или количества используемой памяти, а здесь это не нужно

2019-05-03 09:09 UTC, SpirinEgor commented on hw04/task1/src/main/java/group144/afrikanov/LinkedList.java
> +     * @param value - value which is need to add
Насколько я знаю, ты можешь добавлять модификатор в наследуемом классе.
```(Java)
class A {
    public void func() {
        System.out.println("A::f");
    }
}

class B extends A {
    @Override
    public void func() throws ArithmeticException {
        int a = 5 / 0;
    }
}
```

2019-05-03 09:10 UTC, SpirinEgor commented on hw04/task1/src/test/java/group144/afrikanov/LinkedListTest.java
> +class LinkedListTest<T> {
Ну не только для этого, надо понимать, что метод корректно работает при множественных вызовах.

2019-05-03 09:16 UTC, afrikanov commented on hw04/task1/src/test/java/group144/afrikanov/LinkedListTest.java
> +class LinkedListTest<T> {
Так если метод, например, правильно удаляет 1 ноду, то в цикле, где он будет удалять 1000 нод, он тоже будет правильно работать, просто нужно протестить все комбинации разных методов

2019-05-04 16:56 UTC, SpirinEgor commented on hw04/task1/src/main/java/group144/afrikanov/LinkedList.java
> +        if (item == null) {
Я бы нее сказал, что это какое-то интуитивное поведение. Скорее надо бросать ошибку всегда, если пытаемся вставить после чего-то, но этого после не существует.

2019-05-04 16:56 UTC, SpirinEgor commented on hw04/task1/src/main/java/group144/afrikanov/LinkedList.java
>          ++size;
У тебя где-то `++size`, а где-то `size++`. В современных компиляторах уже нет разницы, что использовать, но хотелось бы какой-то единообразности.

2019-05-04 16:56 UTC, SpirinEgor commented on hw04/task1/src/main/java/group144/afrikanov/UniqueList.java
> +        if (search(value) == null) {
В методе выше вызывается как раз таки через `super`, работать будут оба варианты, но опять же хотелось бы единообразия.

2019-05-04 16:56 UTC, SpirinEgor commented on hw04/task1/src/main/java/group144/afrikanov/UniqueList.java
>       * @throws ValueAlreadyExistsException when the value already exists
Если метод кидает два вида ошибок, то и указать надо оба.

2019-05-04 16:56 UTC, SpirinEgor commented on hw04/task1/src/main/java/group144/afrikanov/LinkedList.java
> +    public void insertAfter(Node<T> item, T value) throws InvalidInputNode {
Ещё JavaDoc поправить надо тогда, внести информацию про бросаемую ошибку.

2019-05-04 19:57 UTC, SpirinEgor approved these changes

2019-05-04 19:58 UTC, SpirinEgor commented
По коду всё норм, но давай ещё разберёмся с градлавскими файлами, которые ты хранишь репо.
Точно не надо хранить автосгенерированные скрипты под определённую ось.
Что вам говорили про градл, что надо класть в гит?

2019-05-05 10:30 UTC, afrikanov commented on hw04/task1/src/main/java/group144/afrikanov/LinkedList.java
> +    public void insertAfter(Node<T> item, T value) throws InvalidInputNode {
Говорили, что надо класть все файлы, которые есть у меня, кроме settings, но я подумал, что это не будет лишним

2019-05-05 12:36 UTC, jzuken commented on hw04/task1/src/test/java/group144/afrikanov/LinkedListTest.java
> +class LinkedListTest<T> {
ну совсем не факт. мелкие тесты, разумеется, тоже нужны, но необходимость в больших примерах они не отменяют

2019-05-05 12:38 UTC, jzuken commented
да не, выкладывать целиком gradle wrapper это нормальная практика (сами скрипты, без генерящихся им файлов). может в домашках и не особо оправдано, зато удобно запускать даже на машинах, где gradle не стоит или стоит не той версии

2019-05-05 12:43 UTC, jzuken requested changes

2019-05-05 12:43 UTC, jzuken commented on hw04/task1/src/main/java/group144/afrikanov/IndexOutOfBoundsException.java
> +public class IndexOutOfBoundsException extends RuntimeException {
а чем системное исключение с ровно таким же названием не угодило?

2019-05-05 12:43 UTC, jzuken commented on hw04/task1/src/main/java/group144/afrikanov/InvalidInputNode.java
> +public class InvalidInputNode extends RuntimeException {
к исключениям тоже хорошо бы писать доки

2019-05-05 12:43 UTC, jzuken commented on hw04/task1/src/main/java/group144/afrikanov/InvalidInputNode.java
> +        super("Invalid input node");
этот текст лучше принимать в конструкторе, мало ли чего там захочется из клиентского кода передать

2019-05-05 12:43 UTC, jzuken commented on hw04/task1/src/main/java/group144/afrikanov/LinkedList.java
> +    private Node<T> head = null, tail = null;
лучше не объявлять несколько переменных в одной строке, читаемость важнее

2019-05-05 12:43 UTC, jzuken commented on hw04/task1/src/main/java/group144/afrikanov/LinkedList.java
> +     * @param value - value which is need to add
это правда только для непроверяемых исключений. с проверяемыми всё плохо, приходится укладываться в сигнатуру родительского метода

2019-05-05 12:43 UTC, jzuken commented on hw04/task1/src/main/java/group144/afrikanov/LinkedList.java
> +        } else {
а тут else можно не писать

2019-05-05 12:43 UTC, jzuken commented on hw04/task1/src/main/java/group144/afrikanov/LinkedList.java
> +        } else {
а вот тут его даже стоит не писать. отступ экономится

2019-05-05 12:43 UTC, jzuken commented on hw04/task1/src/main/java/group144/afrikanov/LinkedList.java
> +        public T value;
ну нет, так не пойдёт, особенно с публичными полями. этот класс за пределами списка кому-то нужен вообще? я бы вообще его спрятал, и поля его тоже

2019-05-05 12:43 UTC, jzuken commented on hw04/task1/src/main/java/group144/afrikanov/Main.java
> +public class Main {
это тут не нужно в таком виде

2019-05-05 16:12 UTC, afrikanov commented on hw04/task1/src/main/java/group144/afrikanov/LinkedList.java
> +        } else {
Исправлю, но, как мне кажется, это повышает читабельность

2019-05-05 19:59 UTC, afrikanov commented on hw04/task1/src/main/java/group144/afrikanov/LinkedList.java
> +        public T value;
Я использую его для тестирования. Можно тогда заменить это и добавить геттеры для значений?

2019-05-05 20:28 UTC, afrikanov commented on hw04/task1/src/main/java/group144/afrikanov/LinkedList.java
> +        public T value;
и поставить у Node модификатор protected?

2019-05-07 08:44 UTC, jzuken commented on hw04/task1/src/main/java/group144/afrikanov/LinkedList.java
> +        } else {
наоборот, отступ экономится, меньше скобок, код становится чище

2019-05-07 08:44 UTC, jzuken commented on hw04/task1/src/main/java/group144/afrikanov/LinkedList.java
> +        public T value;
а он нужен кому-то в наследниках? если нет, его надо совсем спрятать, это детали реализации класса, которые не надо выпячивать наружу

2019-05-07 17:06 UTC, afrikanov commented on hw04/task1/src/main/java/group144/afrikanov/LinkedList.java
> +        public T value;
Да, нужен, в UniqueList он передается в качестве параметра для метода

2019-05-09 10:06 UTC, jzuken commented on hw04/task1/src/main/java/group144/afrikanov/LinkedList.java
> +        public T value;
значит это тоже надо поправить, не хочет никто снаружи знать ни про какие ноды, они хотят класть значения в список и получать обратно именно их

2019-05-09 22:10 UTC, SpirinEgor requested changes

2019-05-09 22:10 UTC, SpirinEgor commented on hw04/task1/src/main/java/group144/afrikanov/IndexOutOfBoundsException.java
> +public class IndexOutOfBoundsException extends Exception {
Речь шла о том, что такое исключение уже есть и не надо его заново писать:
https://docs.oracle.com/javase/7/docs/api/java/lang/IndexOutOfBoundsException.html

2019-05-09 22:10 UTC, SpirinEgor commented on hw04/task1/src/main/java/group144/afrikanov/LinkedList.java
> +            throw new ValueNotFoundException("value not found");
Какое-то текстовое значение, которое много используется лучше выносить, как константу. Так будет легче, если захочешь сменить это сообщение.

2019-05-09 22:10 UTC, SpirinEgor commented on hw04/task1/src/main/java/group144/afrikanov/UniqueList.java
> +            throw new ValueAlreadyExistsException("value already exists");
Это тоже к константам относится.

2019-05-10 05:34 UTC, afrikanov commented on hw04/task1/src/main/java/group144/afrikanov/UniqueList.java
> +            throw new ValueAlreadyExistsException("value already exists");
Исправил

2019-05-11 10:18 UTC, SpirinEgor commented
А что насчёт использования встроенного класса ошибки выхода за предела массива?
И совет, называть коммиты не `fixed task`, а более конкретно описывать, что было сделано, потом будет легче ориентироваться в них.

2019-05-11 12:20 UTC, afrikanov commented
> А что насчёт использования встроенного класса ошибки выхода за предела массива?
> И совет, называть коммиты не `fixed task`, а более конкретно описывать, что было сделано, потом будет легче ориентироваться в них.

Так я же убрал собственногаписанное исключение

2019-05-14 16:55 UTC, SpirinEgor commented
> > А что насчёт использования встроенного класса ошибки выхода за предела массива?
> > И совет, называть коммиты не `fixed task`, а более конкретно описывать, что было сделано, потом будет легче ориентироваться в них.
> 
> Так я же убрал собственногаписанное исключение
Действитетельно, не заметил

2019-05-17 12:54 UTC, jzuken commented on hw04/task1/src/main/java/group144/afrikanov/UniqueList.java
> +        } else {
обычно всё же наоборот делают, если что-то пошло не так, бросается исключение, а вся остальная логика уже потом

2019-05-17 12:55 UTC, merged