added task 5.2
afrikanov/Spbu-sem2 pull request #13
Opened 2019-04-11 19:36 UTC by afrikanov

2019-05-05 13:00 UTC, jzuken requested changes

2019-05-05 13:00 UTC, jzuken commented on hw05/task2/src/main/resources/group144.afrikanov/sample.fxml
> +<AnchorPane maxHeight="-Infinity" maxWidth="-Infinity" minHeight="-Infinity" minWidth="-Infinity" prefHeight="100.0" prefWidth="314.0" xmlns="http://javafx.com/javafx/11.0.1" xmlns:fx="http://javafx.
а вот тут уже ничего не зумится, и это грустно

2019-05-05 13:00 UTC, jzuken commented on hw05/task2/src/main/resources/group144.afrikanov/sample.fxml
> +      <Spinner fx:id="firstOperand" layoutX="9.0" layoutY="37.0" prefHeight="25.0" prefWidth="75.0" />
почему оно ниже 0 не опускается?

2019-05-05 13:00 UTC, jzuken commented on hw05/task2/src/main/java/group144/afrikanov/Controller.java
> +                    result.setText(Double.toString(Double.valueOf(first) / Double.valueOf(second)));
а зачем тут боксинг?

2019-05-05 13:00 UTC, jzuken commented on hw05/task2/src/main/java/group144/afrikanov/Controller.java
> +    private void count(int first, int second, char action) {
вот в такой реализации часть с логикой приложения (подсчёт выражения) неотделима от части обработки UI. её же отдельно не протестировать даже никак. надо разделить их на две сущности

2019-06-10 14:20 UTC, jzuken requested changes

2019-06-10 14:20 UTC, jzuken commented on hw05/task2/src/main/java/group144/afrikanov/Controller.java
> +                if (answer != null) {
копипаста

2019-06-10 14:20 UTC, jzuken commented
и про меньше нуля всё ещё актуальрно

2019-06-10 18:47 UTC, afrikanov commented on hw05/task2/src/main/resources/group144.afrikanov/sample.fxml
> +      <Spinner fx:id="firstOperand" layoutX="9.0" layoutY="37.0" prefHeight="25.0" prefWidth="75.0" />
Что именно должно опускаться?

2019-06-10 19:48 UTC, jzuken commented on hw05/task2/src/main/resources/group144.afrikanov/sample.fxml
> +      <Spinner fx:id="firstOperand" layoutX="9.0" layoutY="37.0" prefHeight="25.0" prefWidth="75.0" />
ну значения в полях для ввода

2019-06-11 09:34 UTC, jzuken requested changes

2019-06-11 09:34 UTC, jzuken commented on hw05/task2/src/main/java/group144/afrikanov/Controller.java
> +        ChangeListener changeListener = new ChangeListener() {
ну вообще это генерик тип

2019-06-13 10:49 UTC, merged