added task 5.3
afrikanov/Spbu-sem2 pull request #14
Opened 2019-04-11 19:39 UTC by afrikanov

2019-05-05 13:04 UTC, jzuken requested changes

2019-05-05 13:04 UTC, jzuken commented on hw05/task3/src/main/resources/group144.afrikanov/sample.fxml
> +<AnchorPane maxHeight="-Infinity" maxWidth="-Infinity" minHeight="-Infinity" minWidth="-Infinity" prefHeight="396.0" prefWidth="355.0" xmlns="http://javafx.com/javafx/11.0.1" xmlns:fx="http://javafx.
то, что кнопки операций неактивные -- плохое решение, непонятно же, нажалось оно или нет

2019-05-05 13:04 UTC, jzuken commented on hw05/task3/src/main/resources/group144.afrikanov/sample.fxml
> +   <children>
и тут тоже проблемы с зумом

2019-05-05 13:04 UTC, jzuken commented on hw05/task3/src/main/java/group144/afrikanov/SqrtFromNegativeDigit.java
> +public class SqrtFromNegativeDigit extends Exception {
не надо экономить на именах. и к исключениям тоже надо писать доки

2019-05-05 13:04 UTC, jzuken commented on hw05/task3/src/main/java/group144/afrikanov/Controller.java
> +                if (firstOperand >= 0) {
тут протсо копипаста два раза

2019-05-05 13:04 UTC, jzuken commented on hw05/task3/src/main/java/group144/afrikanov/Controller.java
> +                    secondOperand = Double.valueOf(i);
тут тоже непонятно зачем боксинг

2019-05-05 13:04 UTC, jzuken commented on hw05/task3/src/main/java/group144/afrikanov/Controller.java
> +        if (actionEvent.getSource() instanceof Button) {
ну и здесь та же история с разделением логики и графики. на логику вообще тесты надо написать, но сейчас этого не сделать никак

2019-06-10 14:24 UTC, jzuken requested changes

2019-06-10 14:24 UTC, jzuken commented on hw05/task3/src/main/resources/group144.afrikanov/sample.fxml
> +<AnchorPane maxHeight="-Infinity" maxWidth="-Infinity" minHeight="-Infinity" minWidth="-Infinity" prefHeight="396.0" prefWidth="348.0" xmlns="http://javafx.com/javafx/11.0.1" xmlns:fx="http://javafx.
форму можно уменьшить до не юзабельного состояния

2019-06-10 14:24 UTC, jzuken commented on hw05/task3/src/main/java/group144/afrikanov/Controller.java
> +                firstOperand = firstOperand * 10 + inputNumber;
копипаста

2019-06-10 14:24 UTC, jzuken commented on hw05/task3/src/test/java/group144/afrikanov/ControllerTest.java
> +    void expressionSumTest() throws DivisionByZeroException, SqrtFromNegativeDigit {
а тут бы не помешали ещё и отрицательные тесты. например, когда несколько операций подряд идут и т.п.

2019-06-10 18:22 UTC, afrikanov commented on hw05/task3/src/test/java/group144/afrikanov/ControllerTest.java
> +    void expressionSumTest() throws DivisionByZeroException, SqrtFromNegativeDigit {
Так они же есть в expressionCombinedTest()

2019-06-11 09:35 UTC, jzuken commented
запускаю калькулятор, жму 5, мне пишет "-5". это как-то странно

2019-06-13 10:53 UTC, merged