added task 04.2
afrikanov/Spbu-sem2 pull request #17
Opened 2019-04-26 04:38 UTC by afrikanov

2019-05-11 10:13 UTC, jzuken requested changes

2019-05-11 10:13 UTC, jzuken commented on hw04/task2/src/main/java/group144/afrikanov/AVLTree.java
> +    public int getHeight(Node<T> node) {
а почему бы его не сделать методом самой ноды?

2019-05-11 10:13 UTC, jzuken commented on hw04/task2/src/main/java/group144/afrikanov/AVLTree.java
> +    public Node<T> rotateRight(Node<T> node) {
это всё методы не дерева, а ноды. дерево тут вообще никак не используется

2019-05-11 10:13 UTC, jzuken commented on hw04/task2/src/main/java/group144/afrikanov/AVLTree.java
> +        Node (Type key, Node<Type> parent) {
модификаторы доступа потерялись

2019-05-11 10:13 UTC, jzuken commented on hw04/task2/src/main/java/group144/afrikanov/AVLTree.java
> +    public class Node<Type extends Comparable<Type>> implements Comparable<Node<Type>> {
не нужен он никому за пределами класса, не надо делать его публичным

2019-05-11 10:13 UTC, jzuken commented on hw04/task2/src/main/java/group144/afrikanov/TreeIterator.java
> +public class TreeIterator <T extends Comparable<T>> implements Iterator<T> {
и этот тоже должен быть вложенным в дерево

2019-05-11 10:13 UTC, jzuken commented on hw04/task2/src/main/java/group144/afrikanov/TreeIterator.java
> +            for ( ; ;) {
не надо так делать

2019-05-11 10:13 UTC, jzuken commented on hw04/task2/src/main/java/group144/afrikanov/TreeIterator.java
> +}
тесты?

2019-05-11 19:48 UTC, afrikanov commented on hw04/task2/src/main/java/group144/afrikanov/AVLTree.java
> +    public int getHeight(Node<T> node) {
Потому что там предусмотрена проверка на null

2019-05-11 19:56 UTC, afrikanov commented on hw04/task2/src/main/java/group144/afrikanov/TreeIterator.java
> +public class TreeIterator <T extends Comparable<T>> implements Iterator<T> {
тогда смысла в геттерах вообще не будет, если все эти классы будут лежать в 1 большом

2019-05-17 14:33 UTC, jzuken commented on hw04/task2/src/main/java/group144/afrikanov/AVLTree.java
> +    public int getHeight(Node<T> node) {
я не понял, у тебя процедура, которая работает со своим аргументом, а я предлагаю сделать её методом соответствующего объекта

2019-05-17 14:33 UTC, jzuken commented on hw04/task2/src/main/java/group144/afrikanov/TreeIterator.java
> +public class TreeIterator <T extends Comparable<T>> implements Iterator<T> {
так и не надо их

2019-05-20 19:48 UTC, afrikanov commented on hw04/task2/src/main/java/group144/afrikanov/AVLTree.java
> +    public int getHeight(Node<T> node) {
Когда процедура, то в ней я могу проверить объект на null и вернуть соответствующий результат, а когда это метод объекта, то мне каждый раз при вызове этого объекта придется проверять его на null, иначе я вызову null.getHeight и поймаю исключение

2019-05-20 19:48 UTC, afrikanov commented on hw04/task2/src/main/java/group144/afrikanov/AVLTree.java
> +    public int getHeight(Node<T> node) {
Но ладно, я исправил

2019-06-10 11:18 UTC, merged