added task 2.2
afrikanov/Spbu-sem2 pull request #4
Opened 2019-03-11 22:23 UTC by afrikanov

2019-04-13 19:41 UTC, ujohnny commented on hw02/task2/src/task2/hw2/afrikanov/Calculator.java
> +                    int value = stack.top();
все эти операции -- копипаста. исправить

2019-04-14 12:09 UTC, afrikanov commented on hw02/task2/src/task2/hw2/afrikanov/Calculator.java
> +                    int value = stack.top();
А что конкретно здесь нужно исправить?

2019-04-14 18:34 UTC, ujohnny commented on hw02/task2/src/task2/hw2/afrikanov/Calculator.java
> +                    int value = stack.top();
уменьшить количество копипасты

2019-04-29 08:13 UTC, jzuken requested changes

2019-04-29 08:13 UTC, jzuken commented on hw02/task2/src/task2/hw2/afrikanov/Calculator.java
> +                    int value = stack.top();
то есть обобщить код, выполняемый внутри кейсов

2019-04-29 08:13 UTC, jzuken commented on hw02/task2/src/task2/hw2/afrikanov/Calculator.java
> +                        newInteger += inputString.charAt(j);
для наращивания строк надо использовать StringBuilder, иначе крайне неэффективно память расходуется. оно на каждую новую строку новый объект создаёт

2019-04-29 08:13 UTC, jzuken commented on hw02/task2/src/task2/hw2/afrikanov/Stack.java
> +public interface Stack {
интерфейсы тоже надо документировать

2019-04-29 08:13 UTC, jzuken commented on hw02/task2/src/task2/hw2/afrikanov/StackArray.java
> +public class StackArray implements Stack{
пробел

2019-04-29 08:13 UTC, jzuken commented on hw02/task2/src/task2/hw2/afrikanov/StackArray.java
> +    final int MAXN = (int)1e5;
не самое лучшее имя, лучше назвать типа MAX_SIZE или как-то так

2019-04-29 08:13 UTC, jzuken commented on hw02/task2/src/task2/hw2/afrikanov/StackArray.java
> +        stack[size] = value;
а переполнение массива оно не учитывает?

2019-04-29 08:13 UTC, jzuken commented on hw02/task2/src/task2/hw2/afrikanov/StackArray.java
> +            return;
тут надо кидать исключение по идее

2019-04-29 08:13 UTC, jzuken commented on hw02/task2/src/task2/hw2/afrikanov/StackArray.java
> +        else  {
а тут лишний пробел

2019-04-29 08:13 UTC, jzuken commented on hw02/task2/src/task2/hw2/afrikanov/StackArray.java
> +    public boolean empty() {
лучше назвать isEmpty

2019-05-11 10:57 UTC, jzuken requested changes

2019-05-11 10:57 UTC, jzuken commented on hw02/task2/src/task2/hw2/afrikanov/Calculator.java
> +            char strVal = inputString.charAt(i);
не надо экономить на именах переменных

2019-05-11 10:57 UTC, jzuken commented on hw02/task2/src/task2/hw2/afrikanov/StackArray.java
> +    private final int MAX_SIZE = (int)1e5;
по стайлгайду капсом пишутся только статические константы

2019-05-11 10:57 UTC, jzuken commented on hw02/task2/src/task2/hw2/afrikanov/StackArray.java
> +    private Type top = null;
такие инициализации вируальная машина делает сама

2019-05-11 10:57 UTC, jzuken commented on hw02/task2/src/task2/hw2/afrikanov/StackList.java
> +        Node(Type value, Node<T> next) {
модификатор доступа

2019-06-10 10:55 UTC, merged