added task 3.1
afrikanov/Spbu-sem2 pull request #9
Opened 2019-04-10 22:52 UTC by afrikanov

2019-04-13 19:44 UTC, ujohnny commented on hw03/task1/src/main/java/group144/afrikanov/HashTable.java
> +        if (table.get(item).size() == 1) {
а если там уже несколько элементов?

2019-04-14 12:58 UTC, afrikanov commented on hw03/task1/src/main/java/group144/afrikanov/HashTable.java
> +        if (table.get(item).size() == 1) {
То эту конфликтную ячейку мы уже посчитали ранее

2019-05-05 12:34 UTC, jzuken requested changes

2019-05-05 12:34 UTC, jzuken commented on hw03/task1/src/main/java/group144/afrikanov/HashTable.java
> +        if (table.get(item).size() == 1) {
в смысле? я ничего не понял. а если у двух разных строк хешкод совпал?

2019-05-05 13:19 UTC, jzuken commented
найди 10 отличий: https://github.com/Degiv/spbsu_homework/pull/44/files/bbe6b3a157783b8e889f99428aab6835597ccbb1#diff-bd2518c5842b21f8c743e3137c65280c
ещё раз увижу такое, получишь персональные домашки, совсем другой сложности

2019-06-10 11:15 UTC, merged